"""Static seed data for airports and metropolitan airport groups.

Kept as plain data (not DB rows) so both the Alembic migration and
in-memory test databases can seed from the same source of truth.
"""

# code -> (name, city, country)
AIRPORTS: dict[str, tuple[str, str, str]] = {
    # Poland
    "WAW": ("Warsaw Chopin Airport", "Warsaw", "Poland"),
    "WMI": ("Warsaw Modlin Airport", "Warsaw", "Poland"),
    "KRK": ("Kraków John Paul II Airport", "Kraków", "Poland"),
    "GDN": ("Gdańsk Lech Wałęsa Airport", "Gdańsk", "Poland"),
    "WRO": ("Wrocław Copernicus Airport", "Wrocław", "Poland"),
    "POZ": ("Poznań-Ławica Airport", "Poznań", "Poland"),
    "KTW": ("Katowice Airport", "Katowice", "Poland"),
    "RZE": ("Rzeszów-Jasionka Airport", "Rzeszów", "Poland"),
    "LUZ": ("Lublin Airport", "Lublin", "Poland"),
    "SZZ": ("Szczecin-Goleniów Airport", "Szczecin", "Poland"),
    "BZG": ("Bydgoszcz Ignacy Jan Paderewski Airport", "Bydgoszcz", "Poland"),
    # UK & Ireland
    "LHR": ("Heathrow Airport", "London", "United Kingdom"),
    "LGW": ("Gatwick Airport", "London", "United Kingdom"),
    "STN": ("Stansted Airport", "London", "United Kingdom"),
    "LTN": ("Luton Airport", "London", "United Kingdom"),
    "LCY": ("London City Airport", "London", "United Kingdom"),
    "SEN": ("Southend Airport", "London", "United Kingdom"),
    "MAN": ("Manchester Airport", "Manchester", "United Kingdom"),
    "EDI": ("Edinburgh Airport", "Edinburgh", "United Kingdom"),
    "DUB": ("Dublin Airport", "Dublin", "Ireland"),
    # France / Benelux
    "CDG": ("Charles de Gaulle Airport", "Paris", "France"),
    "ORY": ("Orly Airport", "Paris", "France"),
    "BVA": ("Beauvais-Tillé Airport", "Paris", "France"),
    "NCE": ("Nice Côte d'Azur Airport", "Nice", "France"),
    "AMS": ("Amsterdam Airport Schiphol", "Amsterdam", "Netherlands"),
    "BRU": ("Brussels Airport", "Brussels", "Belgium"),
    "CRL": ("Brussels South Charleroi Airport", "Brussels", "Belgium"),
    # Germany / Austria / Switzerland
    "FRA": ("Frankfurt Airport", "Frankfurt", "Germany"),
    "MUC": ("Munich Airport", "Munich", "Germany"),
    "BER": ("Berlin Brandenburg Airport", "Berlin", "Germany"),
    "DUS": ("Düsseldorf Airport", "Düsseldorf", "Germany"),
    "HAM": ("Hamburg Airport", "Hamburg", "Germany"),
    "VIE": ("Vienna International Airport", "Vienna", "Austria"),
    "ZRH": ("Zurich Airport", "Zurich", "Switzerland"),
    "GVA": ("Geneva Airport", "Geneva", "Switzerland"),
    # Iberia / Italy
    "MAD": ("Adolfo Suárez Madrid-Barajas Airport", "Madrid", "Spain"),
    "BCN": ("Barcelona-El Prat Airport", "Barcelona", "Spain"),
    "AGP": ("Málaga Airport", "Málaga", "Spain"),
    "PMI": ("Palma de Mallorca Airport", "Palma", "Spain"),
    "LIS": ("Humberto Delgado Airport", "Lisbon", "Portugal"),
    "OPO": ("Francisco Sá Carneiro Airport", "Porto", "Portugal"),
    "FCO": ("Leonardo da Vinci-Fiumicino Airport", "Rome", "Italy"),
    "CIA": ("Ciampino Airport", "Rome", "Italy"),
    "MXP": ("Malpensa Airport", "Milan", "Italy"),
    "LIN": ("Linate Airport", "Milan", "Italy"),
    "BGY": ("Il Caravaggio Airport", "Bergamo", "Italy"),
    "VCE": ("Venice Marco Polo Airport", "Venice", "Italy"),
    "NAP": ("Naples International Airport", "Naples", "Italy"),
    # Nordics / Baltics
    "CPH": ("Copenhagen Airport", "Copenhagen", "Denmark"),
    "ARN": ("Stockholm Arlanda Airport", "Stockholm", "Sweden"),
    "OSL": ("Oslo Airport Gardermoen", "Oslo", "Norway"),
    "HEL": ("Helsinki-Vantaa Airport", "Helsinki", "Finland"),
    "KEF": ("Keflavík International Airport", "Reykjavík", "Iceland"),
    "RIX": ("Riga International Airport", "Riga", "Latvia"),
    "TLL": ("Tallinn Airport", "Tallinn", "Estonia"),
    "VNO": ("Vilnius Airport", "Vilnius", "Lithuania"),
    # Central / Eastern Europe
    "PRG": ("Václav Havel Airport Prague", "Prague", "Czech Republic"),
    "BUD": ("Budapest Ferenc Liszt International Airport", "Budapest", "Hungary"),
    "OTP": ("Henri Coandă International Airport", "Bucharest", "Romania"),
    "SOF": ("Sofia Airport", "Sofia", "Bulgaria"),
    "BEG": ("Belgrade Nikola Tesla Airport", "Belgrade", "Serbia"),
    "ZAG": ("Zagreb Airport", "Zagreb", "Croatia"),
    "LJU": ("Ljubljana Jože Pučnik Airport", "Ljubljana", "Slovenia"),
    "SVO": ("Sheremetyevo International Airport", "Moscow", "Russia"),
    "KBP": ("Boryspil International Airport", "Kyiv", "Ukraine"),
    # Greece / Turkey / Middle East
    "ATH": ("Athens International Airport", "Athens", "Greece"),
    "IST": ("Istanbul Airport", "Istanbul", "Turkey"),
    "SAW": ("Sabiha Gökçen Airport", "Istanbul", "Turkey"),
    "DXB": ("Dubai International Airport", "Dubai", "United Arab Emirates"),
    "AUH": ("Abu Dhabi International Airport", "Abu Dhabi", "United Arab Emirates"),
    "DOH": ("Hamad International Airport", "Doha", "Qatar"),
    "TLV": ("Ben Gurion Airport", "Tel Aviv", "Israel"),
    # Asia
    "HND": ("Tokyo Haneda Airport", "Tokyo", "Japan"),
    "NRT": ("Narita International Airport", "Tokyo", "Japan"),
    "KIX": ("Kansai International Airport", "Osaka", "Japan"),
    "ITM": ("Osaka International Airport", "Osaka", "Japan"),
    "NGO": ("Chubu Centrair International Airport", "Nagoya", "Japan"),
    "ICN": ("Incheon International Airport", "Seoul", "South Korea"),
    "GMP": ("Gimpo International Airport", "Seoul", "South Korea"),
    "PEK": ("Beijing Capital International Airport", "Beijing", "China"),
    "PKX": ("Beijing Daxing International Airport", "Beijing", "China"),
    "PVG": ("Shanghai Pudong International Airport", "Shanghai", "China"),
    "SHA": ("Shanghai Hongqiao International Airport", "Shanghai", "China"),
    "HKG": ("Hong Kong International Airport", "Hong Kong", "Hong Kong"),
    "TPE": ("Taiwan Taoyuan International Airport", "Taipei", "Taiwan"),
    "SIN": ("Singapore Changi Airport", "Singapore", "Singapore"),
    "KUL": ("Kuala Lumpur International Airport", "Kuala Lumpur", "Malaysia"),
    "BKK": ("Suvarnabhumi Airport", "Bangkok", "Thailand"),
    "DMK": ("Don Mueang International Airport", "Bangkok", "Thailand"),
    "CGK": ("Soekarno-Hatta International Airport", "Jakarta", "Indonesia"),
    "MNL": ("Ninoy Aquino International Airport", "Manila", "Philippines"),
    "DEL": ("Indira Gandhi International Airport", "Delhi", "India"),
    "BOM": ("Chhatrapati Shivaji Maharaj International Airport", "Mumbai", "India"),
    "BLR": ("Kempegowda International Airport", "Bengaluru", "India"),
    # Americas
    "JFK": ("John F. Kennedy International Airport", "New York", "United States"),
    "EWR": ("Newark Liberty International Airport", "New York", "United States"),
    "LGA": ("LaGuardia Airport", "New York", "United States"),
    "ORD": ("O'Hare International Airport", "Chicago", "United States"),
    "LAX": ("Los Angeles International Airport", "Los Angeles", "United States"),
    "SFO": ("San Francisco International Airport", "San Francisco", "United States"),
    "SEA": ("Seattle-Tacoma International Airport", "Seattle", "United States"),
    "BOS": ("Logan International Airport", "Boston", "United States"),
    "MIA": ("Miami International Airport", "Miami", "United States"),
    "ATL": ("Hartsfield-Jackson Atlanta International Airport", "Atlanta", "United States"),
    "DFW": ("Dallas/Fort Worth International Airport", "Dallas", "United States"),
    "IAH": ("George Bush Intercontinental Airport", "Houston", "United States"),
    "DEN": ("Denver International Airport", "Denver", "United States"),
    "YYZ": ("Toronto Pearson International Airport", "Toronto", "Canada"),
    "YVR": ("Vancouver International Airport", "Vancouver", "Canada"),
    "GRU": ("São Paulo/Guarulhos International Airport", "São Paulo", "Brazil"),
    "GIG": ("Rio de Janeiro/Galeão International Airport", "Rio de Janeiro", "Brazil"),
    "EZE": ("Ministro Pistarini International Airport", "Buenos Aires", "Argentina"),
    "BOG": ("El Dorado International Airport", "Bogotá", "Colombia"),
    "MEX": ("Mexico City International Airport", "Mexico City", "Mexico"),
    "LIM": ("Jorge Chávez International Airport", "Lima", "Peru"),
    "SCL": ("Arturo Merino Benítez International Airport", "Santiago", "Chile"),
    # Oceania
    "SYD": ("Sydney Kingsford Smith Airport", "Sydney", "Australia"),
    "MEL": ("Melbourne Airport", "Melbourne", "Australia"),
    "BNE": ("Brisbane Airport", "Brisbane", "Australia"),
    "AKL": ("Auckland Airport", "Auckland", "New Zealand"),
    # Africa
    "JNB": ("O.R. Tambo International Airport", "Johannesburg", "South Africa"),
    "CPT": ("Cape Town International Airport", "Cape Town", "South Africa"),
    "CAI": ("Cairo International Airport", "Cairo", "Egypt"),
    "NBO": ("Jomo Kenyatta International Airport", "Nairobi", "Kenya"),
    "ADD": ("Addis Ababa Bole International Airport", "Addis Ababa", "Ethiopia"),
    "LOS": ("Murtala Muhammed International Airport", "Lagos", "Nigeria"),
}

# group_code -> (group_name, member codes)
GROUPS: dict[str, tuple[str, tuple[str, ...]]] = {
    "TYO": ("Tokyo (all airports)", ("HND", "NRT")),
    "OSA": ("Osaka (all airports)", ("KIX", "ITM")),
    "LON": ("London (all airports)", ("LHR", "LGW", "STN", "LTN", "LCY", "SEN")),
    "NYC": ("New York (all airports)", ("JFK", "EWR", "LGA")),
    "PAR": ("Paris (all airports)", ("CDG", "ORY", "BVA")),
    "ROM": ("Rome (all airports)", ("FCO", "CIA")),
    "MIL": ("Milan (all airports)", ("MXP", "LIN", "BGY")),
    "SEL": ("Seoul (all airports)", ("ICN", "GMP")),
    "BJS": ("Beijing (all airports)", ("PEK", "PKX")),
    "SHG": ("Shanghai (all airports)", ("PVG", "SHA")),
    "THB": ("Bangkok (all airports)", ("BKK", "DMK")),
}
