"""initial schema

Revision ID: 465067facec3
Revises: 
Create Date: 2026-08-19 18:19:00.225244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '465067facec3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airport_groups',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('airports',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('searches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('earliest_departure', sa.Date(), nullable=False),
    sa.Column('latest_departure', sa.Date(), nullable=False),
    sa.Column('min_trip_days', sa.Integer(), nullable=False),
    sa.Column('max_trip_days', sa.Integer(), nullable=False),
    sa.Column('latest_return', sa.Date(), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('max_stops', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('schedule', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airport_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_code', sa.String(length=3), nullable=False),
    sa.Column('airport_code', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['airport_code'], ['airports.code'], ),
    sa.ForeignKeyConstraint(['group_code'], ['airport_groups.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airport_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_airport_group_members_group_code'), ['group_code'], unique=False)

    op.create_table('search_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('combinations_total', sa.Integer(), nullable=False),
    sa.Column('combinations_checked', sa.Integer(), nullable=False),
    sa.Column('offers_found', sa.Integer(), nullable=False),
    sa.Column('offers_new', sa.Integer(), nullable=False),
    sa.Column('offers_verified', sa.Integer(), nullable=False),
    sa.Column('errors', sa.Text(), nullable=False),
    sa.Column('current_query', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.Integer(), nullable=False),
    sa.Column('first_seen_run_id', sa.Integer(), nullable=False),
    sa.Column('last_seen_run_id', sa.Integer(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('trip_days', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('airline', sa.String(length=80), nullable=False),
    sa.Column('marketing_airlines', sa.String(length=120), nullable=False),
    sa.Column('operating_airlines', sa.String(length=120), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('stop_airports', sa.Text(), nullable=False),
    sa.Column('ticket_type', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('booking_source', sa.String(length=80), nullable=True),
    sa.Column('booking_url', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_offer_id', sa.String(length=160), nullable=False),
    sa.Column('identity_key', sa.String(length=300), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['first_seen_run_id'], ['search_runs.id'], ),
    sa.ForeignKeyConstraint(['last_seen_run_id'], ['search_runs.id'], ),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('search_id', 'identity_key', name='uq_flight_offer_search_identity')
    )
    with op.batch_alter_table('flight_offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_flight_offers_identity_key'), ['identity_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_offers_last_seen_run_id'), ['last_seen_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_flight_offers_search_id'), ['search_id'], unique=False)

    op.create_table('provider_errors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('return_date', sa.Date(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_errors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_errors_search_run_id'), ['search_run_id'], unique=False)

    op.create_table('flight_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_offer_id', sa.Integer(), nullable=False),
    sa.Column('segment_number', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('flight_number', sa.String(length=20), nullable=False),
    sa.Column('marketing_airline', sa.String(length=10), nullable=False),
    sa.Column('operating_airline', sa.String(length=10), nullable=False),
    sa.Column('departure_airport', sa.String(length=3), nullable=False),
    sa.Column('arrival_airport', sa.String(length=3), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('arrival_time', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['flight_offer_id'], ['flight_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_offer_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=40), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sent_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flight_offer_id'], ['flight_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flight_offer_id', 'notification_type', 'price')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_flight_offer_id'), ['flight_offer_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flight_offer_id', sa.Integer(), nullable=False),
    sa.Column('search_run_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('checked_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['flight_offer_id'], ['flight_offers.id'], ),
    sa.ForeignKeyConstraint(['search_run_id'], ['search_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_checked_at'), ['checked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_flight_offer_id'), ['flight_offer_id'], unique=False)

    # ### end Alembic commands ###
    # --- Seed built-in airport groups (plan §7: e.g. TYO -> HND + NRT) ---
    airport_groups_table = sa.table(
        "airport_groups", sa.column("code", sa.String), sa.column("name", sa.String)
    )
    airports_table = sa.table(
        "airports",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("city", sa.String),
        sa.column("country", sa.String),
    )
    airport_group_members_table = sa.table(
        "airport_group_members", sa.column("group_code", sa.String), sa.column("airport_code", sa.String)
    )

    op.bulk_insert(
        airport_groups_table,
        [
            {"code": "TYO", "name": "Tokyo"},
            {"code": "LON", "name": "London"},
            {"code": "NYC", "name": "New York"},
        ],
    )
    op.bulk_insert(
        airports_table,
        [
            {"code": "HND", "name": "Tokyo Haneda", "city": "Tokyo", "country": "Japan"},
            {"code": "NRT", "name": "Tokyo Narita", "city": "Tokyo", "country": "Japan"},
            {"code": "LHR", "name": "London Heathrow", "city": "London", "country": "United Kingdom"},
            {"code": "LGW", "name": "London Gatwick", "city": "London", "country": "United Kingdom"},
            {"code": "STN", "name": "London Stansted", "city": "London", "country": "United Kingdom"},
            {"code": "LTN", "name": "London Luton", "city": "London", "country": "United Kingdom"},
            {"code": "JFK", "name": "John F. Kennedy International", "city": "New York", "country": "United States"},
            {"code": "EWR", "name": "Newark Liberty International", "city": "New York", "country": "United States"},
            {"code": "LGA", "name": "LaGuardia", "city": "New York", "country": "United States"},
        ],
    )
    op.bulk_insert(
        airport_group_members_table,
        [
            {"group_code": "TYO", "airport_code": "HND"},
            {"group_code": "TYO", "airport_code": "NRT"},
            {"group_code": "LON", "airport_code": "LHR"},
            {"group_code": "LON", "airport_code": "LGW"},
            {"group_code": "LON", "airport_code": "STN"},
            {"group_code": "LON", "airport_code": "LTN"},
            {"group_code": "NYC", "airport_code": "JFK"},
            {"group_code": "NYC", "airport_code": "EWR"},
            {"group_code": "NYC", "airport_code": "LGA"},
        ],
    )
    # ### end seed data ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_history_flight_offer_id'))
        batch_op.drop_index(batch_op.f('ix_price_history_checked_at'))

    op.drop_table('price_history')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_flight_offer_id'))

    op.drop_table('notifications')
    op.drop_table('flight_segments')
    with op.batch_alter_table('provider_errors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_errors_search_run_id'))

    op.drop_table('provider_errors')
    with op.batch_alter_table('flight_offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_flight_offers_search_id'))
        batch_op.drop_index(batch_op.f('ix_flight_offers_last_seen_run_id'))
        batch_op.drop_index(batch_op.f('ix_flight_offers_identity_key'))

    op.drop_table('flight_offers')
    op.drop_table('search_runs')
    with op.batch_alter_table('airport_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_airport_group_members_group_code'))

    op.drop_table('airport_group_members')
    op.drop_table('searches')
    op.drop_table('airports')
    op.drop_table('airport_groups')
    # ### end Alembic commands ###
